// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package collector

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type networkIoCall struct {
	_         structs.HostLayout
	Buffer    uint64
	Requested uint32
	Fd        int32
	Direction uint8
	Reserved  [7]uint8
	Tuple     struct {
		_             structs.HostLayout
		Family        uint16
		Protocol      uint16
		LocalPort     uint16
		RemotePort    uint16
		LocalAddress  [16]uint8
		RemoteAddress [16]uint8
	}
}

type networkProtocolKey struct {
	_        structs.HostLayout
	Pid      uint32
	Fd       int32
	Source   uint8
	Reserved [3]uint8
}

type networkSrttSampleState struct {
	_           structs.HostLayout
	EmittedAtNs uint64
	SrttUs      uint32
	Reserved    uint32
}

type networkSslCall struct {
	_          structs.HostLayout
	Context    uint64
	Buffer     uint64
	SizeOutput uint64
	Fd         int32
	Reserved   uint32
	Tuple      struct {
		_             structs.HostLayout
		Family        uint16
		Protocol      uint16
		LocalPort     uint16
		RemotePort    uint16
		LocalAddress  [16]uint8
		RemoteAddress [16]uint8
	}
}

type networkSslKey struct {
	_        structs.HostLayout
	Pid      uint32
	Reserved uint32
	Context  uint64
}

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	networkMapBioFds                          = "bio_fds"
	networkMapBioNewSocketCalls               = "bio_new_socket_calls"
	networkMapDropCounters                    = "drop_counters"
	networkMapEvents                          = "events"
	networkMapHttp2Connections                = "http2_connections"
	networkMapIoCalls                         = "io_calls"
	networkMapSrttSamples                     = "srtt_samples"
	networkMapSslFds                          = "ssl_fds"
	networkMapSslReadCalls                    = "ssl_read_calls"
	networkMapSslReadExCalls                  = "ssl_read_ex_calls"
	networkMapSslWriteCalls                   = "ssl_write_calls"
	networkMapSslWriteExCalls                 = "ssl_write_ex_calls"
	networkProgObserveBioFreeArm64            = "observe_bio_free_arm64"
	networkProgObserveBioFreeX86              = "observe_bio_free_x86"
	networkProgObserveBioIntCtrlArm64         = "observe_bio_int_ctrl_arm64"
	networkProgObserveBioIntCtrlX86           = "observe_bio_int_ctrl_x86"
	networkProgObserveBioNewSocketArm64       = "observe_bio_new_socket_arm64"
	networkProgObserveBioNewSocketReturnArm64 = "observe_bio_new_socket_return_arm64"
	networkProgObserveBioNewSocketReturnX86   = "observe_bio_new_socket_return_x86"
	networkProgObserveBioNewSocketX86         = "observe_bio_new_socket_x86"
	networkProgObserveEnterClose              = "observe_enter_close"
	networkProgObserveEnterRead               = "observe_enter_read"
	networkProgObserveEnterRecvfrom           = "observe_enter_recvfrom"
	networkProgObserveEnterSendto             = "observe_enter_sendto"
	networkProgObserveEnterWrite              = "observe_enter_write"
	networkProgObserveExitRead                = "observe_exit_read"
	networkProgObserveExitRecvfrom            = "observe_exit_recvfrom"
	networkProgObserveExitSendto              = "observe_exit_sendto"
	networkProgObserveExitWrite               = "observe_exit_write"
	networkProgObserveSslFreeArm64            = "observe_ssl_free_arm64"
	networkProgObserveSslFreeX86              = "observe_ssl_free_x86"
	networkProgObserveSslReadArm64            = "observe_ssl_read_arm64"
	networkProgObserveSslReadExArm64          = "observe_ssl_read_ex_arm64"
	networkProgObserveSslReadExReturnArm64    = "observe_ssl_read_ex_return_arm64"
	networkProgObserveSslReadExReturnX86      = "observe_ssl_read_ex_return_x86"
	networkProgObserveSslReadExX86            = "observe_ssl_read_ex_x86"
	networkProgObserveSslReadReturnArm64      = "observe_ssl_read_return_arm64"
	networkProgObserveSslReadReturnX86        = "observe_ssl_read_return_x86"
	networkProgObserveSslReadX86              = "observe_ssl_read_x86"
	networkProgObserveSslSetBioArm64          = "observe_ssl_set_bio_arm64"
	networkProgObserveSslSetBioX86            = "observe_ssl_set_bio_x86"
	networkProgObserveSslSetFdArm64           = "observe_ssl_set_fd_arm64"
	networkProgObserveSslSetFdX86             = "observe_ssl_set_fd_x86"
	networkProgObserveSslWriteArm64           = "observe_ssl_write_arm64"
	networkProgObserveSslWriteExArm64         = "observe_ssl_write_ex_arm64"
	networkProgObserveSslWriteExReturnArm64   = "observe_ssl_write_ex_return_arm64"
	networkProgObserveSslWriteExReturnX86     = "observe_ssl_write_ex_return_x86"
	networkProgObserveSslWriteExX86           = "observe_ssl_write_ex_x86"
	networkProgObserveSslWriteReturnArm64     = "observe_ssl_write_return_arm64"
	networkProgObserveSslWriteReturnX86       = "observe_ssl_write_return_x86"
	networkProgObserveSslWriteX86             = "observe_ssl_write_x86"
	networkProgObserveTcpConnect              = "observe_tcp_connect"
	networkProgObserveTcpRecvmsg              = "observe_tcp_recvmsg"
	networkProgObserveTcpSendmsg              = "observe_tcp_sendmsg"
)

// loadNetwork returns the embedded CollectionSpec for network.
func loadNetwork() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_NetworkBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load network: %w", err)
	}

	return spec, err
}

// loadNetworkObjects loads network and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*networkObjects
//	*networkPrograms
//	*networkMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadNetworkObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := loadNetwork()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// networkSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type networkSpecs struct {
	networkProgramSpecs
	networkMapSpecs
	networkVariableSpecs
}

// networkProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type networkProgramSpecs struct {
	ObserveBioFreeArm64            *ebpf.ProgramSpec `ebpf:"observe_bio_free_arm64"`
	ObserveBioFreeX86              *ebpf.ProgramSpec `ebpf:"observe_bio_free_x86"`
	ObserveBioIntCtrlArm64         *ebpf.ProgramSpec `ebpf:"observe_bio_int_ctrl_arm64"`
	ObserveBioIntCtrlX86           *ebpf.ProgramSpec `ebpf:"observe_bio_int_ctrl_x86"`
	ObserveBioNewSocketArm64       *ebpf.ProgramSpec `ebpf:"observe_bio_new_socket_arm64"`
	ObserveBioNewSocketReturnArm64 *ebpf.ProgramSpec `ebpf:"observe_bio_new_socket_return_arm64"`
	ObserveBioNewSocketReturnX86   *ebpf.ProgramSpec `ebpf:"observe_bio_new_socket_return_x86"`
	ObserveBioNewSocketX86         *ebpf.ProgramSpec `ebpf:"observe_bio_new_socket_x86"`
	ObserveEnterClose              *ebpf.ProgramSpec `ebpf:"observe_enter_close"`
	ObserveEnterRead               *ebpf.ProgramSpec `ebpf:"observe_enter_read"`
	ObserveEnterRecvfrom           *ebpf.ProgramSpec `ebpf:"observe_enter_recvfrom"`
	ObserveEnterSendto             *ebpf.ProgramSpec `ebpf:"observe_enter_sendto"`
	ObserveEnterWrite              *ebpf.ProgramSpec `ebpf:"observe_enter_write"`
	ObserveExitRead                *ebpf.ProgramSpec `ebpf:"observe_exit_read"`
	ObserveExitRecvfrom            *ebpf.ProgramSpec `ebpf:"observe_exit_recvfrom"`
	ObserveExitSendto              *ebpf.ProgramSpec `ebpf:"observe_exit_sendto"`
	ObserveExitWrite               *ebpf.ProgramSpec `ebpf:"observe_exit_write"`
	ObserveSslFreeArm64            *ebpf.ProgramSpec `ebpf:"observe_ssl_free_arm64"`
	ObserveSslFreeX86              *ebpf.ProgramSpec `ebpf:"observe_ssl_free_x86"`
	ObserveSslReadArm64            *ebpf.ProgramSpec `ebpf:"observe_ssl_read_arm64"`
	ObserveSslReadExArm64          *ebpf.ProgramSpec `ebpf:"observe_ssl_read_ex_arm64"`
	ObserveSslReadExReturnArm64    *ebpf.ProgramSpec `ebpf:"observe_ssl_read_ex_return_arm64"`
	ObserveSslReadExReturnX86      *ebpf.ProgramSpec `ebpf:"observe_ssl_read_ex_return_x86"`
	ObserveSslReadExX86            *ebpf.ProgramSpec `ebpf:"observe_ssl_read_ex_x86"`
	ObserveSslReadReturnArm64      *ebpf.ProgramSpec `ebpf:"observe_ssl_read_return_arm64"`
	ObserveSslReadReturnX86        *ebpf.ProgramSpec `ebpf:"observe_ssl_read_return_x86"`
	ObserveSslReadX86              *ebpf.ProgramSpec `ebpf:"observe_ssl_read_x86"`
	ObserveSslSetBioArm64          *ebpf.ProgramSpec `ebpf:"observe_ssl_set_bio_arm64"`
	ObserveSslSetBioX86            *ebpf.ProgramSpec `ebpf:"observe_ssl_set_bio_x86"`
	ObserveSslSetFdArm64           *ebpf.ProgramSpec `ebpf:"observe_ssl_set_fd_arm64"`
	ObserveSslSetFdX86             *ebpf.ProgramSpec `ebpf:"observe_ssl_set_fd_x86"`
	ObserveSslWriteArm64           *ebpf.ProgramSpec `ebpf:"observe_ssl_write_arm64"`
	ObserveSslWriteExArm64         *ebpf.ProgramSpec `ebpf:"observe_ssl_write_ex_arm64"`
	ObserveSslWriteExReturnArm64   *ebpf.ProgramSpec `ebpf:"observe_ssl_write_ex_return_arm64"`
	ObserveSslWriteExReturnX86     *ebpf.ProgramSpec `ebpf:"observe_ssl_write_ex_return_x86"`
	ObserveSslWriteExX86           *ebpf.ProgramSpec `ebpf:"observe_ssl_write_ex_x86"`
	ObserveSslWriteReturnArm64     *ebpf.ProgramSpec `ebpf:"observe_ssl_write_return_arm64"`
	ObserveSslWriteReturnX86       *ebpf.ProgramSpec `ebpf:"observe_ssl_write_return_x86"`
	ObserveSslWriteX86             *ebpf.ProgramSpec `ebpf:"observe_ssl_write_x86"`
	ObserveTcpConnect              *ebpf.ProgramSpec `ebpf:"observe_tcp_connect"`
	ObserveTcpRecvmsg              *ebpf.ProgramSpec `ebpf:"observe_tcp_recvmsg"`
	ObserveTcpSendmsg              *ebpf.ProgramSpec `ebpf:"observe_tcp_sendmsg"`
}

// networkMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type networkMapSpecs struct {
	BioFds            *ebpf.MapSpec `ebpf:"bio_fds"`
	BioNewSocketCalls *ebpf.MapSpec `ebpf:"bio_new_socket_calls"`
	DropCounters      *ebpf.MapSpec `ebpf:"drop_counters"`
	Events            *ebpf.MapSpec `ebpf:"events"`
	Http2Connections  *ebpf.MapSpec `ebpf:"http2_connections"`
	IoCalls           *ebpf.MapSpec `ebpf:"io_calls"`
	SrttSamples       *ebpf.MapSpec `ebpf:"srtt_samples"`
	SslFds            *ebpf.MapSpec `ebpf:"ssl_fds"`
	SslReadCalls      *ebpf.MapSpec `ebpf:"ssl_read_calls"`
	SslReadExCalls    *ebpf.MapSpec `ebpf:"ssl_read_ex_calls"`
	SslWriteCalls     *ebpf.MapSpec `ebpf:"ssl_write_calls"`
	SslWriteExCalls   *ebpf.MapSpec `ebpf:"ssl_write_ex_calls"`
}

// networkVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type networkVariableSpecs struct {
}

// networkObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadNetworkObjects or ebpf.CollectionSpec.LoadAndAssign.
type networkObjects struct {
	networkPrograms
	networkMaps
	networkVariables
}

func (o *networkObjects) Close() error {
	return _NetworkClose(
		&o.networkPrograms,
		&o.networkMaps,
	)
}

// networkMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadNetworkObjects or ebpf.CollectionSpec.LoadAndAssign.
type networkMaps struct {
	BioFds            *ebpf.Map `ebpf:"bio_fds"`
	BioNewSocketCalls *ebpf.Map `ebpf:"bio_new_socket_calls"`
	DropCounters      *ebpf.Map `ebpf:"drop_counters"`
	Events            *ebpf.Map `ebpf:"events"`
	Http2Connections  *ebpf.Map `ebpf:"http2_connections"`
	IoCalls           *ebpf.Map `ebpf:"io_calls"`
	SrttSamples       *ebpf.Map `ebpf:"srtt_samples"`
	SslFds            *ebpf.Map `ebpf:"ssl_fds"`
	SslReadCalls      *ebpf.Map `ebpf:"ssl_read_calls"`
	SslReadExCalls    *ebpf.Map `ebpf:"ssl_read_ex_calls"`
	SslWriteCalls     *ebpf.Map `ebpf:"ssl_write_calls"`
	SslWriteExCalls   *ebpf.Map `ebpf:"ssl_write_ex_calls"`
}

func (m *networkMaps) Close() error {
	return _NetworkClose(
		m.BioFds,
		m.BioNewSocketCalls,
		m.DropCounters,
		m.Events,
		m.Http2Connections,
		m.IoCalls,
		m.SrttSamples,
		m.SslFds,
		m.SslReadCalls,
		m.SslReadExCalls,
		m.SslWriteCalls,
		m.SslWriteExCalls,
	)
}

// networkVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadNetworkObjects or ebpf.CollectionSpec.LoadAndAssign.
type networkVariables struct {
}

// networkPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadNetworkObjects or ebpf.CollectionSpec.LoadAndAssign.
type networkPrograms struct {
	ObserveBioFreeArm64            *ebpf.Program `ebpf:"observe_bio_free_arm64"`
	ObserveBioFreeX86              *ebpf.Program `ebpf:"observe_bio_free_x86"`
	ObserveBioIntCtrlArm64         *ebpf.Program `ebpf:"observe_bio_int_ctrl_arm64"`
	ObserveBioIntCtrlX86           *ebpf.Program `ebpf:"observe_bio_int_ctrl_x86"`
	ObserveBioNewSocketArm64       *ebpf.Program `ebpf:"observe_bio_new_socket_arm64"`
	ObserveBioNewSocketReturnArm64 *ebpf.Program `ebpf:"observe_bio_new_socket_return_arm64"`
	ObserveBioNewSocketReturnX86   *ebpf.Program `ebpf:"observe_bio_new_socket_return_x86"`
	ObserveBioNewSocketX86         *ebpf.Program `ebpf:"observe_bio_new_socket_x86"`
	ObserveEnterClose              *ebpf.Program `ebpf:"observe_enter_close"`
	ObserveEnterRead               *ebpf.Program `ebpf:"observe_enter_read"`
	ObserveEnterRecvfrom           *ebpf.Program `ebpf:"observe_enter_recvfrom"`
	ObserveEnterSendto             *ebpf.Program `ebpf:"observe_enter_sendto"`
	ObserveEnterWrite              *ebpf.Program `ebpf:"observe_enter_write"`
	ObserveExitRead                *ebpf.Program `ebpf:"observe_exit_read"`
	ObserveExitRecvfrom            *ebpf.Program `ebpf:"observe_exit_recvfrom"`
	ObserveExitSendto              *ebpf.Program `ebpf:"observe_exit_sendto"`
	ObserveExitWrite               *ebpf.Program `ebpf:"observe_exit_write"`
	ObserveSslFreeArm64            *ebpf.Program `ebpf:"observe_ssl_free_arm64"`
	ObserveSslFreeX86              *ebpf.Program `ebpf:"observe_ssl_free_x86"`
	ObserveSslReadArm64            *ebpf.Program `ebpf:"observe_ssl_read_arm64"`
	ObserveSslReadExArm64          *ebpf.Program `ebpf:"observe_ssl_read_ex_arm64"`
	ObserveSslReadExReturnArm64    *ebpf.Program `ebpf:"observe_ssl_read_ex_return_arm64"`
	ObserveSslReadExReturnX86      *ebpf.Program `ebpf:"observe_ssl_read_ex_return_x86"`
	ObserveSslReadExX86            *ebpf.Program `ebpf:"observe_ssl_read_ex_x86"`
	ObserveSslReadReturnArm64      *ebpf.Program `ebpf:"observe_ssl_read_return_arm64"`
	ObserveSslReadReturnX86        *ebpf.Program `ebpf:"observe_ssl_read_return_x86"`
	ObserveSslReadX86              *ebpf.Program `ebpf:"observe_ssl_read_x86"`
	ObserveSslSetBioArm64          *ebpf.Program `ebpf:"observe_ssl_set_bio_arm64"`
	ObserveSslSetBioX86            *ebpf.Program `ebpf:"observe_ssl_set_bio_x86"`
	ObserveSslSetFdArm64           *ebpf.Program `ebpf:"observe_ssl_set_fd_arm64"`
	ObserveSslSetFdX86             *ebpf.Program `ebpf:"observe_ssl_set_fd_x86"`
	ObserveSslWriteArm64           *ebpf.Program `ebpf:"observe_ssl_write_arm64"`
	ObserveSslWriteExArm64         *ebpf.Program `ebpf:"observe_ssl_write_ex_arm64"`
	ObserveSslWriteExReturnArm64   *ebpf.Program `ebpf:"observe_ssl_write_ex_return_arm64"`
	ObserveSslWriteExReturnX86     *ebpf.Program `ebpf:"observe_ssl_write_ex_return_x86"`
	ObserveSslWriteExX86           *ebpf.Program `ebpf:"observe_ssl_write_ex_x86"`
	ObserveSslWriteReturnArm64     *ebpf.Program `ebpf:"observe_ssl_write_return_arm64"`
	ObserveSslWriteReturnX86       *ebpf.Program `ebpf:"observe_ssl_write_return_x86"`
	ObserveSslWriteX86             *ebpf.Program `ebpf:"observe_ssl_write_x86"`
	ObserveTcpConnect              *ebpf.Program `ebpf:"observe_tcp_connect"`
	ObserveTcpRecvmsg              *ebpf.Program `ebpf:"observe_tcp_recvmsg"`
	ObserveTcpSendmsg              *ebpf.Program `ebpf:"observe_tcp_sendmsg"`
}

func (p *networkPrograms) Close() error {
	return _NetworkClose(
		p.ObserveBioFreeArm64,
		p.ObserveBioFreeX86,
		p.ObserveBioIntCtrlArm64,
		p.ObserveBioIntCtrlX86,
		p.ObserveBioNewSocketArm64,
		p.ObserveBioNewSocketReturnArm64,
		p.ObserveBioNewSocketReturnX86,
		p.ObserveBioNewSocketX86,
		p.ObserveEnterClose,
		p.ObserveEnterRead,
		p.ObserveEnterRecvfrom,
		p.ObserveEnterSendto,
		p.ObserveEnterWrite,
		p.ObserveExitRead,
		p.ObserveExitRecvfrom,
		p.ObserveExitSendto,
		p.ObserveExitWrite,
		p.ObserveSslFreeArm64,
		p.ObserveSslFreeX86,
		p.ObserveSslReadArm64,
		p.ObserveSslReadExArm64,
		p.ObserveSslReadExReturnArm64,
		p.ObserveSslReadExReturnX86,
		p.ObserveSslReadExX86,
		p.ObserveSslReadReturnArm64,
		p.ObserveSslReadReturnX86,
		p.ObserveSslReadX86,
		p.ObserveSslSetBioArm64,
		p.ObserveSslSetBioX86,
		p.ObserveSslSetFdArm64,
		p.ObserveSslSetFdX86,
		p.ObserveSslWriteArm64,
		p.ObserveSslWriteExArm64,
		p.ObserveSslWriteExReturnArm64,
		p.ObserveSslWriteExReturnX86,
		p.ObserveSslWriteExX86,
		p.ObserveSslWriteReturnArm64,
		p.ObserveSslWriteReturnX86,
		p.ObserveSslWriteX86,
		p.ObserveTcpConnect,
		p.ObserveTcpRecvmsg,
		p.ObserveTcpSendmsg,
	)
}

func _NetworkClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed network_bpfel.o
var _NetworkBytes []byte
